// swift-tools-version: 5.9

// WARNING: This file is automatically generated. The PackageDescription is
// only declared here so that Swift Playgrounds and Xcode can recognise the
// .swiftpm directory as an iOS App project.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "OrchidCapture",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "OrchidCapture",
            targets: ["AppModule"],
            bundleIdentifier: "land.deno.orchid.capture",
            teamIdentifier: "",
            displayVersion: "0.1",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .leaf),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [.phone],
            supportedInterfaceOrientations: [.portrait],
            capabilities: [
                .microphone(purposeString: "Record voice notes to capture as Orchid drafts."),
                .speechRecognition(purposeString: "Transcribe voice notes on-device so you can edit before sending.")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
